const data = [
  {
    id: 1,
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    image: "https://spoonacular.com/recipeImages/632788-556x370.jpg",
    title: "salad",
  },
  {
    id: 2,
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    image: "https://spoonacular.com/recipeImages/649183-556x370.jpg",
    title: "meatloaf",
  },
  {
    id: 3,
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    image: "https://spoonacular.com/recipeImages/634429-556x370.jpg",
    title: "dip",
  },
  {
    id: 4,
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    image: "https://spoonacular.com/recipeImages/660932-556x370.jpg",
    title: "apple juice",
  },
  {
    id: 5,
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    image: "https://spoonacular.com/recipeImages/663950-556x370.jpg",
    title: "pancake",
  },
  {
    id: 6,
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    image: "https://spoonacular.com/recipeImages/652134-556x370.jpg",
    title: "pancake",
  },
  {
    id: 7,
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    image: "https://spoonacular.com/recipeImages/715438-556x370.jpg",
    title: "pancake",
  },
  {
    id: 8,
    vegetarian: true,
    vegan: true,
    glutenFree: false,
    dairyFree: true,
    veryHealthy: false,
    image: "https://spoonacular.com/recipeImages/664975-556x370.jpg",
    title: "salmon",
  },
  {
    id: 9,
    vegetarian: true,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    image: "https://spoonacular.com/recipeImages/657306-556x370.jpg",
    title: "pancake",
  },
  {
    id: 10,
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    image: "https://spoonacular.com/recipeImages/660161-556x370.jpg",
    title: "sauce",
  },
];

export const recipe = {
  title: "dahl",
  image: "https://spoonacular.com/recipeImages/632788-556x370.jpg",
  summary:
    'The recipe Indian Lentil Dahl can be made <b>in about 45 minutes</b>. This recipe makes 4 servings with <b>400 calories</b>, <b>17g of protein</b>, and <b>20g of fat</b> each. For <b>$1.06 per serving</b>, this recipe <b>covers 23%</b> of your daily requirements of vitamins and minerals. It is brought to you by Foodista. A mixture of lime juice, lentils, coconut milk, and a handful of other ingredients are all it takes to make this recipe so yummy. 13 people were glad they tried this recipe. It works well as a main course. It is a <b>rather inexpensive</b> recipe for fans of Indian food. It is a good option if you\'re following a <b>gluten free, dairy free, lacto ovo vegetarian, and vegan</b> diet. Taking all factors into account, this recipe <b>earns a spoonacular score of 75%</b>, which is solid. Similar recipes include <a href="https://spoonacular.com/recipes/indian-spice-52-diet-for-red-lentil-dahl-1368615">Indian Spice – 5:2 Diet for Red Lentil Dahl</a>, <a href="https://spoonacular.com/recipes/indian-spice-52-diet-for-red-lentil-dahl-1201527">Indian Spice – 5:2 Diet for Red Lentil Dahl</a>, and <a href="https://spoonacular.com/recipes/indian-spice-52-diet-for-red-lentil-dahl-666725">Indian Spice – 5:2 Diet for Red Lentil Dahl</a>.',
};

export default data;
